// <auto-generated />
namespace Exercise_1.MovieRentalMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TableVideosColumnGenreIDNameChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableVideosColumnGenreIDNameChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202008242100100_TableVideosColumnGenreIDNameChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
